### ISSUE TITLE
Connection leak

### ISSUE THREAD

**Issue by monktastic** [dnvriend/akka-persistence-jdbc#70]
Howdy,

I'm getting the below stack trace:

```
[warn] 17:43:57.131 ProxyLeakTask  - Connection leak detection triggered for conn147: url=jdbc:h2:file:./var/project/h2-journal/h2:journal user=ROOT, stack trace follows
java.lang.Exception: Apparent connection leak detected
    at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
    at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
    at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
    at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
    at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
    at slick.jdbc.StreamingInvokerAction$class.emitStream(StreamingInvokerAction.scala:28)
    at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.emitStream(JdbcActionComponent.scala:218)
    at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.emitStream(JdbcActionComponent.scala:218)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$3.run(DatabaseComponent.scala:285)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'm using Slick 3.1.1, HikariCP 2.4.7, akka 2.4.9, h2 1.4.192.

Any advice? I don't think I'm doing anything unusual, and I don't touch slick or HikariCP directly.

Thanks!

**Comment by monktastic** [comment]
Ah, just noticed another issue where you suggest using HikariCP 2.3.13. Didn't work for them but maybe it will for us....

**Comment by monktastic** [comment]
Did not fix it.

**Comment by monktastic** [comment]
FYI I increased max connections and threads and the problem has not appeared for a while. Not sure if I just pushed it back. Let's see :)

**Comment by dnvriend** [comment]
Hi, darn the "connection leak" problem is back. This problem seems to arise when the max number of connections and threads have been set to a low setting. We came across this same problem in [Issue #44 Leaking Connections](#44). @prettynatty had this same issue and increased the queue size to 10000 and that seems to work for him. 

For my own projects, I set the values to:

```
jdbc-journal {
slick.db.numThreads = 1000
slick.db.maxConnections = 25
slick.db.minConnections = 2
slick.db.initializationFailFast = false
}

jdbc-snapshot-store {
  slick.db.numThreads = 1000
  slick.db.maxConnections = 5
  slick.db.minConnections = 2
  slick.db.initializationFailFast = false
}

jdbc-read-journal {
  slick.db.numThreads = 1000
  slick.db.maxConnections = 5
  slick.db.minConnections = 2
  slick.db.initializationFailFast = false
}
```

which seems to work as well. 

This problems has been reported to slick [Slick Issue #1492 - Slick runs out of connections during extensive streaming usage](https://github.com/slick/slick/issues/1492), which is related to issue [Slick Issue #1274 - Slick 3.0 transactionally deadlocks](https://github.com/slick/slick/issues/1274) that should be fixed in Slick 3.2.0, when it eventually will be released. The transactional block has been removed from the akka-persistence-jdbc plugin, since it was used for writing to the `deleted_to` table, which does not exists anymore. 

To be honest, Slick has more problems so I await the release of v3.2.0 and see if it is a better library. We will evaluate slick after the next release.
